version: '3'
services:
  filer:
    build: ./docker/apache-php
    ports:
      - 127.0.0.1:80:80
      - 127.0.0.1:443:443
    links:
      - bdd:bdd
    volumes:
      - ./src/:/app/
  bdd:
    image: mariadb:latest
    ports:
      - 127.0.0.1:3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_USER: site_user
      MYSQL_PASSWORD: site_password
      MYSQL_DATABASE: site_bdd
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - bdd
    ports:
      - 127.0.0.1:8080:80
    environment:
      PMA_HOST: bdd
